import { StyleSheet } from '@react-pdf/renderer'

export const COLORS = {
  dark: '#0A0F14',
  emerald: '#10B981',
  emeraldLight: '#D1FAE5',
  emeraldDark: '#064E3B',
  white: '#FFFFFF',
  gray900: '#111827',
  gray700: '#374151',
  gray500: '#6B7280',
  gray200: '#E5E7EB',
  gray100: '#F9FAFB',
  red: '#EF4444',
  redLight: '#FEE2E2',
  amber: '#F59E0B',
  amberLight: '#FEF3C7',
  green: '#22C55E',
  greenLight: '#DCFCE7',
  accent: '#00E676',
  cardBg: '#F8FAFC',
  sectionBg: '#F0FDF4',
}

export const styles = StyleSheet.create({
  page: { fontFamily: 'Helvetica', backgroundColor: COLORS.white, paddingBottom: 36 },
  /** Interior report page: column layout with header + flex content + footer */
  reportInnerPage: {
    fontFamily: 'Helvetica',
    backgroundColor: COLORS.white,
    flexDirection: 'column',
    height: '100%',
  },
  pageInnerContent: {
    flexGrow: 1,
    flexShrink: 1,
    paddingHorizontal: 32,
    paddingTop: 28,
    paddingBottom: 16,
  },
  pageFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 32,
    paddingTop: 8,
    paddingBottom: 12,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.gray200,
    gap: 12,
  },
  footerDisclaimerShort: { fontSize: 6.5, color: COLORS.gray500, lineHeight: 1.35, flexGrow: 1, maxWidth: '72%' },
  footerPageNumber: { fontSize: 7.5, color: COLORS.gray700, fontWeight: 700 },
  pageHeaderPatientCol: { alignItems: 'flex-end', maxWidth: '46%' },
  headerPatientName: { fontSize: 9, fontWeight: 700, color: COLORS.gray900, textAlign: 'right' },
  coverPage: { fontFamily: 'Helvetica', backgroundColor: COLORS.dark, padding: 0 },
  coverTopBar: { backgroundColor: COLORS.emerald, height: 8, width: '100%' },
  coverContent: { padding: 40, flexGrow: 1, justifyContent: 'center', alignItems: 'center' },
  coverBrand: { fontSize: 12, color: COLORS.emerald, fontWeight: 700, letterSpacing: 2, marginBottom: 48 },
  coverBadge: {
    backgroundColor: COLORS.emeraldDark,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.emerald,
  },
  coverBadgeText: { color: COLORS.emerald, fontSize: 9, fontWeight: 700, letterSpacing: 2 },
  coverTitle: {
    fontSize: 36,
    fontWeight: 700,
    color: COLORS.white,
    textAlign: 'center',
    lineHeight: 1.15,
  },
  coverAccent: {
    fontSize: 36,
    fontWeight: 700,
    color: COLORS.accent,
    textAlign: 'center',
    marginBottom: 20,
  },
  coverDivider: { width: 60, height: 1, backgroundColor: '#1a2e1a', marginVertical: 14 },
  coverPreparedFor: { color: '#9CA3AF', fontSize: 11, marginBottom: 6 },
  coverName: { color: COLORS.white, fontSize: 22, fontWeight: 700, textAlign: 'center', marginBottom: 28 },
  coverMetaBox: {
    backgroundColor: '#111820',
    borderRadius: 10,
    padding: 16,
    width: 240,
    borderWidth: 1,
    borderColor: '#1a2e1a',
    alignItems: 'center',
    marginBottom: 40,
  },
  coverMetaText: { color: '#6EE7B7', fontSize: 9, marginBottom: 4, textAlign: 'center' },
  coverStatsRow: {
    flexDirection: 'row',
    backgroundColor: '#0d1520',
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderTopWidth: 1,
    borderTopColor: COLORS.emerald,
  },
  coverStatItem: { flex: 1, alignItems: 'center' },
  coverStatNum: { fontSize: 26, fontWeight: 700, color: COLORS.emerald },
  coverStatNumAccent: { fontSize: 26, fontWeight: 700, color: COLORS.accent },
  coverStatLabel: { fontSize: 8, color: '#9CA3AF', marginTop: 2, letterSpacing: 1 },
  coverBottom: { padding: 14, alignItems: 'center' },
  coverDisclaimer: { color: '#4B5563', fontSize: 7.5, textAlign: 'center', paddingHorizontal: 24 },
  /** Full-bleed area behind cover copy (relative for absolute deco images). */
  coverBodyRelative: { flexGrow: 1, position: 'relative', width: '100%' },
  coverHeroDeco: {
    position: 'absolute',
    top: 80,
    right: 0,
    width: 280,
    height: 320,
    opacity: 0.15,
    borderRadius: 12,
  },
  coverBottomLeftDeco: {
    position: 'absolute',
    bottom: 80,
    left: 0,
    width: 180,
    height: 200,
    opacity: 0.15,
    borderRadius: 10,
  },
  coverBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 48,
    width: '100%',
  },
  coverBrandText: { fontSize: 14, color: COLORS.emerald, fontWeight: 700, letterSpacing: 2, marginLeft: 8 },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.gray200,
    backgroundColor: COLORS.white,
  },
  pageHeaderBrandWrap: { flexDirection: 'row', alignItems: 'center', maxWidth: '72%' },
  headerBrand: { fontSize: 10, fontWeight: 700, color: COLORS.gray900, marginLeft: 6 },
  headerMeta: { fontSize: 8, color: COLORS.gray500 },
  pageFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 32,
    paddingTop: 6,
    paddingBottom: 10,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.gray200,
    backgroundColor: COLORS.white,
  },
  footerText: { fontSize: 7.5, color: COLORS.gray500 },
  pageFooterFixed: {
    position: 'absolute',
    bottom: 18,
    left: 32,
    right: 32,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.gray200,
    backgroundColor: COLORS.white,
  },
  topAccentBar: { backgroundColor: COLORS.emerald, height: 4, width: '100%' },
  content: { paddingHorizontal: 32, paddingTop: 12, paddingBottom: 8, flexGrow: 1 },
  sectionLabel: { fontSize: 9, fontWeight: 700, color: COLORS.emerald, letterSpacing: 2, marginBottom: 4 },
  sectionTitle: { fontSize: 20, fontWeight: 700, color: COLORS.gray900, marginBottom: 4 },
  sectionSubtitle: { fontSize: 10, color: COLORS.gray500, marginBottom: 10, lineHeight: 1.5 },
  sectionDivider: { height: 2, backgroundColor: COLORS.emerald, marginBottom: 14, width: 48 },
  scoreCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 10,
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
  },
  scoreBig: { fontSize: 48, fontWeight: 700, color: COLORS.emerald, width: 88 },
  scoreSlash: { fontSize: 16, color: COLORS.gray500, marginTop: 20, marginRight: 6 },
  scoreMeta: { flex: 1 },
  scoreStatus: { fontSize: 14, fontWeight: 700, color: COLORS.emerald, marginBottom: 4 },
  scoreNote: { fontSize: 9.5, color: COLORS.gray500, lineHeight: 1.45 },
  subScoreRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  subScoreLabel: { fontSize: 9, fontWeight: 700, color: COLORS.gray700, width: 96 },
  subScoreBarBg: { flexGrow: 1, height: 8, backgroundColor: COLORS.gray200, borderRadius: 4, marginHorizontal: 8 },
  subScoreBarFill: { height: 8, borderRadius: 4 },
  subScoreNum: { fontSize: 9, fontWeight: 700, width: 34, textAlign: 'right' },
  subScoreNote: { fontSize: 8, color: COLORS.gray500, lineHeight: 1.4, marginTop: 2, marginLeft: 104, marginBottom: 6 },
  defCard: { borderRadius: 10, padding: 14, marginBottom: 10, borderWidth: 0.5, borderColor: COLORS.gray200 },
  defCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  defNutrient: { fontSize: 15, fontWeight: 700, color: COLORS.gray900, flexGrow: 1, paddingRight: 8 },
  severityBadge: { borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3 },
  severityText: { fontSize: 8, fontWeight: 700, letterSpacing: 0.8 },
  defTagline: { fontSize: 10, fontWeight: 700, color: COLORS.gray700, marginBottom: 6, fontStyle: 'italic' },
  severityBarOuter: { height: 4, borderRadius: 2, overflow: 'hidden', marginBottom: 8, backgroundColor: COLORS.gray200 },
  severityBarInner: { height: 4, borderRadius: 2 },
  defLabel: { fontSize: 8.5, fontWeight: 700, color: COLORS.gray900, marginBottom: 3, marginTop: 8 },
  defBody: { fontSize: 9.8, color: COLORS.gray700, lineHeight: 1.55 },
  symptomRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 3, marginLeft: 2 },
  symptomDotOuter: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.emerald,
    marginRight: 8,
    marginTop: 3,
    flexShrink: 0,
  },
  symptomText: { fontSize: 9.5, color: COLORS.gray700, flexGrow: 1, lineHeight: 1.45 },
  tableHeader: { flexDirection: 'row', backgroundColor: COLORS.dark, paddingVertical: 7, paddingHorizontal: 8 },
  tableHeaderText: { fontSize: 8, fontWeight: 700, color: COLORS.emerald, letterSpacing: 0.6 },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 0.3,
    borderBottomColor: COLORS.gray200,
  },
  tableRowAlt: { backgroundColor: COLORS.gray100 },
  tableCellText: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.45 },
  tableEmphasisEmerald: { fontSize: 9, fontWeight: 700, color: COLORS.emerald, fontStyle: 'italic' },
  mealDayHeaderBox: {
    backgroundColor: COLORS.dark,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginTop: 8,
    marginBottom: 6,
    borderRadius: 6,
  },
  mealDayTexts: { flexGrow: 1, paddingRight: 8 },
  mealDayHeaderText: { color: COLORS.white, fontSize: 10, fontWeight: 700 },
  mealDayFocus: { color: COLORS.emerald, fontSize: 8.5, marginTop: 2 },
  suppCard: {
    backgroundColor: COLORS.sectionBg,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.emerald,
  },
  suppName: { fontSize: 13, fontWeight: 700, color: COLORS.gray900, marginBottom: 6 },
  suppStatPillWrap: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 6 },
  suppStat: {
    backgroundColor: COLORS.white,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
    marginRight: 6,
    marginBottom: 6,
  },
  suppStatLabel: { fontSize: 7, color: COLORS.gray500, letterSpacing: 0.3 },
  suppStatVal: { fontSize: 9, fontWeight: 700, color: COLORS.gray900 },
  suppParaLabel: { fontSize: 8.5, fontWeight: 700, marginTop: 4, marginBottom: 2 },
  suppSafety: { fontSize: 8.5, color: COLORS.emeraldDark, lineHeight: 1.45, marginTop: 4 },
  checkRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 5 },
  checkBullet: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.emerald,
    marginRight: 8,
    marginTop: 2,
    flexShrink: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkMark: { color: COLORS.white, fontSize: 8, fontWeight: 700 },
  checkText: { fontSize: 9.5, color: COLORS.gray700, flexGrow: 1, lineHeight: 1.45 },
  timelineRow: { flexDirection: 'row', marginBottom: 10 },
  timelineLeft: { width: 72, paddingRight: 8 },
  timelinePeriod: { fontSize: 9, fontWeight: 700, color: COLORS.emerald },
  timelinePhase: { fontSize: 8, color: COLORS.gray500 },
  timelineContent: {
    flexGrow: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: 8,
    padding: 10,
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
  },
  timelineArrow: { fontSize: 10, color: COLORS.emerald, marginLeft: 72, marginBottom: 4 },
  doctorCard: {
    backgroundColor: COLORS.sectionBg,
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.emerald,
    marginTop: 10,
  },
  doctorNote: { fontSize: 10, color: COLORS.gray700, lineHeight: 1.65, fontStyle: 'italic' },
  doctorSig: { fontSize: 10, fontWeight: 700, color: COLORS.gray900, marginTop: 10 },
  doctorCred: { fontSize: 8.5, color: COLORS.gray500, marginTop: 2 },
  summaryNum: { fontSize: 22, fontWeight: 700, width: 28, color: COLORS.emerald },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 0.3,
    borderBottomColor: COLORS.gray200,
  },
  summaryText: { fontSize: 10, color: COLORS.gray700, flexGrow: 1, lineHeight: 1.45 },
  avoidFood: { fontSize: 9.5, fontWeight: 700, color: COLORS.red },
  avoidWhy: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.45 },
  avoidSwap: { fontSize: 9.5, fontWeight: 700, color: COLORS.emerald },
  insightCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
    flexDirection: 'row',
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
  },
  insightSvg: { marginRight: 10, marginTop: 2, width: 12, height: 12 },
  insightText: { fontSize: 9.5, color: COLORS.gray700, flexGrow: 1, lineHeight: 1.5 },
  /** Health score section: relative root for corner wellness image */
  healthScoreSectionOuter: { position: 'relative', width: '100%', paddingRight: 112, marginBottom: 4 },
  healthWellnessCircle: {
    position: 'absolute',
    top: 56,
    right: 24,
    width: 100,
    height: 100,
    borderRadius: 50,
    opacity: 0.8,
  },
  sectionBannerWide: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 12,
  },
  mealPlanBannerImg: { height: 90, opacity: 0.85 },
  supplementBannerImg: { height: 80, opacity: 0.7 },
  timelineBannerImg: { height: 70, opacity: 0.6 },
  mealDayThumb: { width: 36, height: 36, borderRadius: 18 },
  supplementCardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  suppTitleBlock: { flexGrow: 1, paddingRight: 8 },
  supplementThumbCircular: { width: 52, height: 52, borderRadius: 26 },
  defCardOuterRow: { flexDirection: 'row', alignItems: 'flex-start' },
  defCardTextCol: { flexGrow: 1, paddingRight: 8 },
  defCardImageCol: { width: 90, alignItems: 'center', justifyContent: 'flex-start', paddingTop: 2 },
  defCardThumbSq: { width: 80, height: 80, borderRadius: 8, opacity: 0.9 },
  foodsSplitRow: { flexDirection: 'row', marginBottom: 12, alignItems: 'stretch' },
  foodsSplitCol: { flexGrow: 1 },
  foodsSplitMiddle: {
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    flexShrink: 0,
  },
  foodsSplitArrow: { fontSize: 16, color: COLORS.emerald, fontWeight: 900 },
  foodsSplitAvoidImg: { width: '100%', height: 60, borderRadius: 8, opacity: 0.6 },
  foodsSplitEatImg: { width: '100%', height: 60, borderRadius: 8 },
  foodsSplitLabelAvoid: {
    fontSize: 8,
    color: COLORS.red,
    fontWeight: 700,
    textAlign: 'center',
    marginTop: 4,
  },
  foodsSplitLabelEat: {
    fontSize: 8,
    color: COLORS.emerald,
    fontWeight: 700,
    textAlign: 'center',
    marginTop: 4,
  },
  doctorSigRow: { flexDirection: 'row', alignItems: 'center', marginTop: 14 },
  doctorAvatar: { width: 48, height: 48, borderRadius: 24, marginRight: 12 },
  doctorSigName: { fontSize: 11, fontWeight: 700, color: COLORS.gray900 },
  doctorSigLine: { fontSize: 8.5, color: COLORS.gray500, marginTop: 2 },
  blockSpacer: { height: 10 },
  smallFootnote: { fontSize: 7.5, color: COLORS.gray500, lineHeight: 1.5, marginTop: 8 },
  /** Gut health & premium sections */
  absorptionScoreRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  absorptionScoreTextCol: { flexGrow: 1 },
  absorptionLabel: { fontSize: 10, fontWeight: 700, color: COLORS.gray900, marginBottom: 4 },
  absorptionNoteText: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.45 },
  nutrientPairTableTitle: { fontSize: 11, fontWeight: 700, color: COLORS.gray900, marginBottom: 3 },
  nutrientPairTableSub: { fontSize: 8.5, color: COLORS.gray500, marginBottom: 8, lineHeight: 1.4 },
  nutrientPairRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 0.3,
    borderBottomColor: COLORS.gray200,
  },
  nutrientPairName: { width: '32%', fontSize: 9.5, fontWeight: 700, color: COLORS.emerald, paddingRight: 6 },
  nutrientPairPlus: { width: '8%', fontSize: 12, fontWeight: 700, color: COLORS.gray500, textAlign: 'center' },
  nutrientPairWhy: { width: '60%', fontSize: 9, color: COLORS.gray700, lineHeight: 1.45 },
  probioticGridTitle: { fontSize: 11, fontWeight: 700, color: COLORS.gray900, marginTop: 10, marginBottom: 8 },
  probioticGrid: { marginTop: 4 },
  probioticGridRow: { flexDirection: 'row', marginBottom: 6 },
  probioticCard: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: COLORS.cardBg,
    borderRadius: 8,
    padding: 10,
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
    alignItems: 'center',
  },
  probioticCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.emeraldLight,
    marginBottom: 6,
  },
  probioticName: { fontSize: 9, fontWeight: 700, color: COLORS.gray900, textAlign: 'center' },
  probioticQty: { fontSize: 8, color: COLORS.gray500, textAlign: 'center', marginTop: 2 },
  absorptionTipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
  },
  tipNumCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: COLORS.emerald,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    flexShrink: 0,
  },
  tipNumText: { fontSize: 10, fontWeight: 700, color: COLORS.white },
  tipTextCol: { flexGrow: 1 },
  tipBold: { fontSize: 9.5, fontWeight: 700, color: COLORS.gray900, lineHeight: 1.4 },
  tipReason: { fontSize: 8.5, color: COLORS.gray500, fontStyle: 'italic', marginTop: 3, lineHeight: 1.45 },
  stressImpactCard: {
    backgroundColor: COLORS.dark,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  stressImpactText: { fontSize: 9.5, color: COLORS.gray200, lineHeight: 1.5, marginBottom: 10 },
  stressNutrientRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8, paddingTop: 4 },
  stressNutrientName: { fontSize: 9.5, fontWeight: 700, color: COLORS.emerald, width: '28%', paddingRight: 6 },
  stressNutrientWhy: { fontSize: 9, color: COLORS.gray500, lineHeight: 1.45, flexGrow: 1 },
  warnIcon: { fontSize: 10, color: COLORS.amber, marginRight: 6, marginTop: 1 },
  breathingCard: {
    borderWidth: 1.5,
    borderColor: COLORS.emerald,
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: COLORS.sectionBg,
  },
  breathingTitle: { fontSize: 10, fontWeight: 700, color: COLORS.emeraldDark, marginBottom: 6 },
  breathingBody: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.5, marginBottom: 10 },
  breathingRow: { flexDirection: 'row', justifyContent: 'space-between' },
  breathingSquare: {
    flexGrow: 1,
    marginHorizontal: 3,
    backgroundColor: COLORS.dark,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  breathingNum: { fontSize: 16, fontWeight: 700, color: COLORS.emerald },
  breathingLbl: { fontSize: 7, color: COLORS.gray500, marginTop: 4, textAlign: 'center' },
  weekendTipCard: {
    borderWidth: 1.5,
    borderColor: COLORS.amber,
    borderRadius: 10,
    padding: 10,
    marginTop: 4,
    backgroundColor: COLORS.amberLight,
  },
  weekendTipText: { fontSize: 9, color: COLORS.gray900, lineHeight: 1.5 },
  labIntro: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.5, marginBottom: 10 },
  labCard: {
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: COLORS.gray200,
    padding: 10,
    marginBottom: 8,
    backgroundColor: COLORS.cardBg,
  },
  labCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
  labTestTitle: { fontSize: 12, fontWeight: 700, color: COLORS.gray900, flexGrow: 1, paddingRight: 8 },
  labCostPill: {
    backgroundColor: COLORS.amberLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  labCostPillText: { fontSize: 8, fontWeight: 700, color: COLORS.amber },
  labWhy: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.45, marginBottom: 8 },
  labMiniRow: { flexDirection: 'row', marginBottom: 6 },
  labMiniCol: { flexGrow: 1, marginRight: 6 },
  labMiniLbl: { fontSize: 7, color: COLORS.gray500, marginBottom: 2 },
  labMiniVal: { fontSize: 8.5, fontWeight: 700, color: COLORS.gray900 },
  labWhere: { fontSize: 8, color: COLORS.gray500, lineHeight: 1.4, marginBottom: 4 },
  labCta: { fontSize: 8.5, fontWeight: 700, color: COLORS.emerald },
  labNoteCard: {
    backgroundColor: COLORS.dark,
    borderRadius: 10,
    padding: 12,
    marginTop: 6,
  },
  labNoteText: { fontSize: 8.5, color: COLORS.gray200, lineHeight: 1.5 },
  shopSummaryRow: { flexDirection: 'row', marginBottom: 8 },
  shopPillGreen: {
    flex: 1,
    marginRight: 6,
    backgroundColor: COLORS.greenLight,
    borderRadius: 8,
    padding: 10,
    borderWidth: 0.5,
    borderColor: COLORS.green,
  },
  shopPillBlue: {
    flex: 1,
    backgroundColor: '#E0F2FE',
    borderRadius: 8,
    padding: 10,
    borderWidth: 0.5,
    borderColor: '#38BDF8',
  },
  shopPillTitle: { fontSize: 8, fontWeight: 700, color: COLORS.gray700, marginBottom: 4 },
  shopPillVal: { fontSize: 11, fontWeight: 700, color: COLORS.gray900 },
  shopBudgetBelow: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.45, marginBottom: 10 },
  defTargetPill: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.emeraldLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  defTargetPillText: { fontSize: 7.5, fontWeight: 700, color: COLORS.emeraldDark },
  supplementShopGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  supplementShopCard: {
    width: '47%',
    marginBottom: 6,
    marginRight: '3%',
    backgroundColor: COLORS.sectionBg,
    borderRadius: 8,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.emerald,
  },
  supShopName: { fontSize: 10, fontWeight: 700, color: COLORS.gray900 },
  supShopBrand: { fontSize: 8, color: COLORS.gray500, marginTop: 2 },
  supShopLine: { fontSize: 8.5, color: COLORS.gray700, marginTop: 4 },
  supShopLink: { fontSize: 8, color: COLORS.emerald, fontWeight: 700, marginTop: 4 },
  budgetTipCard: {
    borderWidth: 1.5,
    borderColor: COLORS.emerald,
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
    backgroundColor: COLORS.white,
  },
  budgetTipText: { fontSize: 9, color: COLORS.gray700, lineHeight: 1.5 },
  gutIssuesList: { marginBottom: 8 },
  gutIssueLine: { fontSize: 8.5, color: COLORS.gray700, marginBottom: 3, lineHeight: 1.4 },
  mealPlanCompactRow: { paddingVertical: 4 },
  mealPlanCompactHeader: { paddingVertical: 5, paddingHorizontal: 6 },
})

export function getSeverityStyle(sev: string) {
  const s = sev.toLowerCase()
  if (s === 'high')
    return { bg: COLORS.redLight, border: COLORS.red, text: COLORS.red, bar: COLORS.red, pct: 85 }
  if (s === 'moderate' || s === 'medium')
    return { bg: COLORS.amberLight, border: COLORS.amber, text: COLORS.amber, bar: COLORS.amber, pct: 60 }
  return { bg: COLORS.greenLight, border: COLORS.green, text: COLORS.green, bar: COLORS.green, pct: 30 }
}

export function getSubScoreBarColor(val: number) {
  if (val >= 70) return COLORS.green
  if (val >= 50) return COLORS.amber
  return COLORS.red
}
